### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by EldersJavas** [DrDREAM233/auto-get-fu-card#4]
明天就小年了，同志们冲呀

1. 自定义chrome和chromedriver.exe路径  
 - [x] 命令行版 
- [x] 配置文件版

2. - [ ] 根据Chrome版本自动下载

3. - [x] 修复一堆bug(包括markdown里面的)

4. - [x] Android端短信接收

**Comment by idelin** [comment]
安卓端应该可以全自动吧

**Comment by EldersJavas** [comment]
#6 解决`1`,`3`问题

**Comment by EldersJavas** [comment]
> 安卓端应该可以全自动吧

@idelin 应该可以,现在大佬正在抓紧时间开发

**Comment by idelin** [comment]
o(￣▽￣)ｄ加油

**Comment by EldersJavas** [comment]
Android端短信接收 已完成
